<?php
declare(strict_types=1);
/**
 * One-time installer. Creates config.php, the database tables and the first admin account.
 * After a successful install it refuses to run again (delete config.php to reinstall).
 */
if (PHP_VERSION_ID < 80100) {
    http_response_code(500);
    header("Content-Type: text/html; charset=utf-8");
    exit("<div style=\"font-family:Arial,sans-serif;max-width:560px;margin:60px auto;padding:20px;border:1px solid #f0c0c0;border-radius:10px;background:#fff6f6\"><h2 style=\"margin-top:0\">PHP 8.1 or newer is required</h2><p>This server is running PHP " . PHP_VERSION . ". In cPanel, open <b>MultiPHP Manager</b> (or <b>Select PHP Version</b>), choose PHP 8.1 or newer for this domain, then reload this page.</p></div>");
}

require_once __DIR__ . '/inc/tables.php';

$configFile = __DIR__ . '/config.php';
$errors = [];
$done = false;

if (is_file($configFile)) {
    $cfg = require $configFile;
    try {
        $c = $cfg['db'];
        $pdo = new PDO("mysql:host={$c['host']};port={$c['port']};dbname={$c['name']};charset=utf8mb4", $c['user'], $c['pass'], [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]);
        // Re-running keeps tables in sync with new versions (CREATE IF NOT EXISTS).
        apply_schema($pdo);
        $hasAdmin = (int)$pdo->query("SELECT COUNT(*) FROM users WHERE role='admin'")->fetchColumn() > 0;
    } catch (Throwable $e) {
        $hasAdmin = false;
    }
    if ($hasAdmin) {
        http_response_code(403);
        page('<h1>Already installed</h1><p>The portal is set up. <a href="index.php">Go to sign in</a>.</p><p class="muted">To reinstall, delete <code>config.php</code> from the server first.</p>');
        exit;
    }
}

$detectedBase = (((!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') ? 'https' : 'http') . '://' . ($_SERVER['HTTP_HOST'] ?? 'localhost')
    . rtrim(str_replace('\\', '/', dirname($_SERVER['SCRIPT_NAME'] ?? '/')), '/'));

$v = array_merge([
    'db_host' => 'localhost', 'db_port' => '3306', 'db_name' => '', 'db_user' => '', 'db_pass' => '',
    'app_name' => 'DevTech Staff Portal', 'company' => 'DevTech Hub Ventures', 'base_url' => $detectedBase,
    'address' => 'Ikechy Plaza, Plot 947 Corridor Layout, Shop 17/18 Monaque Junction, Enugu State',
    'admin_name' => '', 'admin_email' => '', 'admin_pass' => '',
], array_map(fn($x) => is_string($x) ? trim($x) : $x, $_POST));

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    if (!filter_var($v['admin_email'], FILTER_VALIDATE_EMAIL)) {
        $errors[] = 'Enter a valid admin email.';
    }
    if (strlen($v['admin_pass']) < 8) {
        $errors[] = 'Admin password needs at least 8 characters.';
    }
    if ($v['admin_name'] === '') {
        $errors[] = 'Enter the admin name.';
    }
    if (!$errors) {
        try {
            $pdo = new PDO("mysql:host={$v['db_host']};port=" . (int)$v['db_port'] . ";dbname={$v['db_name']};charset=utf8mb4", $v['db_user'], $v['db_pass'], [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]);
            apply_schema($pdo);
            $sample = require __DIR__ . '/config.sample.php';
            $sample['app_name'] = $v['app_name'];
            $sample['company'] = $v['company'];
            $sample['address'] = $v['address'];
            $sample['base_url'] = rtrim($v['base_url'], '/');
            $sample['db'] = ['host' => $v['db_host'], 'port' => (int)$v['db_port'], 'name' => $v['db_name'], 'user' => $v['db_user'], 'pass' => $v['db_pass']];
            $sample['smtp']['from_name'] = $v['app_name'];
            $php = "<?php\n// Generated by install.php on " . date('Y-m-d H:i') . "\nreturn " . var_export($sample, true) . ";\n";
            if (file_put_contents($configFile, $php) === false) {
                throw new RuntimeException('Could not write config.php. Check folder permissions (755) and try again.');
            }
            @chmod($configFile, 0640);
            $st = $pdo->prepare("INSERT INTO users (name, email, password_hash, role, active, created_at) VALUES (?, ?, ?, 'admin', 1, NOW())
                                 ON DUPLICATE KEY UPDATE password_hash = VALUES(password_hash), role = 'admin', active = 1");
            $st->execute([$v['admin_name'], strtolower($v['admin_email']), password_hash($v['admin_pass'], PASSWORD_DEFAULT)]);
            $done = true;
        } catch (Throwable $e) {
            $errors[] = 'Setup failed: ' . $e->getMessage();
        }
    }
}

if ($done) {
    page('<h1>You\'re all set</h1><p>The database and admin account are ready.</p><p><a class="btn" href="index.php">Go to sign in</a></p><p class="muted">Next: open <b>Settings</b> to add your SMTP email details, then <b>Staff setup</b> to create staff accounts or <b>Import</b> to bring in your sheets.</p>');
    exit;
}

$e = fn($k) => htmlspecialchars((string)$v[$k], ENT_QUOTES);
$err = $errors ? '<div class="err">' . implode('<br>', array_map('htmlspecialchars', $errors)) . '</div>' : '';
page(<<<HTML
<h1>Install DevTech Staff Portal</h1>
<p class="muted">Create a MySQL database and user in cPanel (MySQL® Databases), give the user ALL PRIVILEGES, then fill this in.</p>
$err
<form method="post" autocomplete="off">
<fieldset><legend>Database</legend>
<label>Host<input name="db_host" value="{$e('db_host')}" required></label>
<label>Port<input name="db_port" value="{$e('db_port')}" required></label>
<label>Database name<input name="db_name" value="{$e('db_name')}" placeholder="cpaneluser_portal" required></label>
<label>Database user<input name="db_user" value="{$e('db_user')}" placeholder="cpaneluser_portal" required></label>
<label>Database password<input type="password" name="db_pass" value="{$e('db_pass')}"></label>
</fieldset>
<fieldset><legend>App</legend>
<label>App name<input name="app_name" value="{$e('app_name')}" required></label>
<label>Company<input name="company" value="{$e('company')}" required></label>
<label>Company address<input name="address" value="{$e('address')}"></label>
<label>Site address (for email links)<input name="base_url" value="{$e('base_url')}"></label>
</fieldset>
<fieldset><legend>First admin account</legend>
<label>Full name<input name="admin_name" value="{$e('admin_name')}" required></label>
<label>Email<input type="email" name="admin_email" value="{$e('admin_email')}" required></label>
<label>Password (8+ characters)<input type="password" name="admin_pass" minlength="8" required></label>
</fieldset>
<button class="btn" type="submit">Install</button>
</form>
HTML);

function page(string $body): void
{
    echo '<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Install · DevTech Staff Portal</title>
<style>body{font-family:system-ui,Segoe UI,Arial,sans-serif;background:#F4F2FD;color:#1f1d2b;margin:0;padding:24px 16px}main{max-width:560px;margin:0 auto;background:#fff;border-radius:14px;padding:24px;border:1px solid #e4e1f5}
h1{font-size:22px;margin:0 0 8px}fieldset{border:1px solid #e4e1f5;border-radius:10px;margin:14px 0;padding:12px 14px}legend{font-weight:600;padding:0 6px}label{display:block;font-size:13px;color:#555;margin:8px 0}
input{display:block;width:100%;box-sizing:border-box;margin-top:4px;padding:10px;border:1px solid #d6d3ea;border-radius:8px;font-size:15px}.btn{display:inline-block;background:#534AB7;color:#fff;border:0;border-radius:8px;padding:11px 18px;font-size:15px;text-decoration:none;cursor:pointer}
.err{background:#FCEBEB;color:#791F1F;border-radius:8px;padding:10px 12px;margin:10px 0}.muted{color:#666;font-size:14px}code{background:#f1effa;padding:1px 5px;border-radius:4px}</style></head><body><main><img src="assets/logo.png" alt="DevTech" height="44" style="display:block;margin-bottom:14px">' . $body . '</main></body></html>';
}
